-- EduNext-AI: A2 kunlik lug'at (30 kun × 20 so'z)
CREATE TABLE IF NOT EXISTS public.vocabulary_list (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  day_number integer NOT NULL CHECK (day_number >= 1 AND day_number <= 30),
  word text NOT NULL,
  translation text NOT NULL,
  level text NOT NULL DEFAULT 'A2'
);

CREATE INDEX IF NOT EXISTS vocabulary_list_day_level_idx
  ON public.vocabulary_list (day_number, level);

ALTER TABLE public.vocabulary_list ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "vocabulary_list_select_public" ON public.vocabulary_list;
CREATE POLICY "vocabulary_list_select_public"
  ON public.vocabulary_list FOR SELECT
  USING (true);

TRUNCATE public.vocabulary_list;

INSERT INTO public.vocabulary_list (day_number, word, translation, level) VALUES
(1, 'hello', 'salom', 'A2'),
(1, 'goodbye', 'xayr', 'A2'),
(1, 'please', 'iltimos', 'A2'),
(1, 'thank you', 'rahmat', 'A2'),
(1, 'sorry', 'kechirasiz', 'A2'),
(1, 'excuse me', 'uzr', 'A2'),
(1, 'yes', 'ha', 'A2'),
(1, 'no', 'yo''q', 'A2'),
(1, 'maybe', 'balki', 'A2'),
(1, 'welcome', 'xush kelibsiz', 'A2'),
(1, 'see you', 'ko''rishguncha', 'A2'),
(1, 'good morning', 'hayirli tong', 'A2'),
(1, 'good night', 'hayirli tun', 'A2'),
(1, 'how are you', 'qandaysiz', 'A2'),
(1, 'fine', 'yahshi', 'A2'),
(1, 'nice to meet you', 'tanishganimdan xursandman', 'A2'),
(1, 'what is your name', 'ismingiz nima', 'A2'),
(1, 'my name is', 'mening ismim', 'A2'),
(1, 'where', 'qayerda', 'A2'),
(1, 'here', 'bu yerda', 'A2'),
(2, 'mother', 'ona', 'A2'),
(2, 'father', 'ota', 'A2'),
(2, 'sister', 'singil', 'A2'),
(2, 'brother', 'aka', 'A2'),
(2, 'parents', 'ota-ona', 'A2'),
(2, 'family', 'oila', 'A2'),
(2, 'child', 'bola', 'A2'),
(2, 'baby', 'chaqaloq', 'A2'),
(2, 'grandfather', 'bobo', 'A2'),
(2, 'grandmother', 'buva', 'A2'),
(2, 'husband', 'er', 'A2'),
(2, 'wife', 'xotin', 'A2'),
(2, 'cousin', 'amakivachcha', 'A2'),
(2, 'uncle', 'amaki', 'A2'),
(2, 'aunt', 'xola', 'A2'),
(2, 'son', 'o''g''il', 'A2'),
(2, 'daughter', 'qiz', 'A2'),
(2, 'relative', 'qarindosh', 'A2'),
(2, 'married', 'uylangan', 'A2'),
(2, 'single', 'boydoq', 'A2'),
(3, 'red', 'qizil', 'A2'),
(3, 'blue', 'ko''k', 'A2'),
(3, 'green', 'yashil', 'A2'),
(3, 'yellow', 'sariq', 'A2'),
(3, 'black', 'qora', 'A2'),
(3, 'white', 'oq', 'A2'),
(3, 'orange', 'apelsin rang', 'A2'),
(3, 'purple', 'binafsha', 'A2'),
(3, 'pink', 'pushti', 'A2'),
(3, 'brown', 'jigarrang', 'A2'),
(3, 'gray', 'kulrang', 'A2'),
(3, 'big', 'katta', 'A2'),
(3, 'small', 'kichik', 'A2'),
(3, 'long', 'uzun', 'A2'),
(3, 'short', 'qisqa', 'A2'),
(3, 'good', 'yahshi', 'A2'),
(3, 'bad', 'yomon', 'A2'),
(3, 'beautiful', 'chiroyli', 'A2'),
(3, 'new', 'yangi', 'A2'),
(3, 'old', 'eski', 'A2'),
(4, 'dog', 'it', 'A2'),
(4, 'cat', 'mushuk', 'A2'),
(4, 'bird', 'qush', 'A2'),
(4, 'fish', 'baliq', 'A2'),
(4, 'horse', 'ot', 'A2'),
(4, 'cow', 'sigir', 'A2'),
(4, 'mouse', 'sichqon', 'A2'),
(4, 'rabbit', 'quyon', 'A2'),
(4, 'lion', 'arslon', 'A2'),
(4, 'tiger', 'yo''lbars', 'A2'),
(4, 'elephant', 'pil', 'A2'),
(4, 'bear', 'ayiq', 'A2'),
(4, 'snake', 'ilon', 'A2'),
(4, 'chicken', 'tovuq', 'A2'),
(4, 'duck', 'o''rdak', 'A2'),
(4, 'sheep', 'qo''y', 'A2'),
(4, 'monkey', 'maymun', 'A2'),
(4, 'animal', 'hayvon', 'A2'),
(4, 'zoo', 'zoopark', 'A2'),
(4, 'pet', 'uy hayvoni', 'A2'),
(5, 'bread', 'non', 'A2'),
(5, 'rice', 'guruch', 'A2'),
(5, 'water', 'suv', 'A2'),
(5, 'milk', 'sut', 'A2'),
(5, 'tea', 'choy', 'A2'),
(5, 'coffee', 'qahva', 'A2'),
(5, 'juice', 'sharbat', 'A2'),
(5, 'meat', 'go''sht', 'A2'),
(5, 'egg', 'tuxum', 'A2'),
(5, 'apple', 'olma', 'A2'),
(5, 'banana', 'banan', 'A2'),
(5, 'orange', 'apelsin', 'A2'),
(5, 'vegetable', 'sabzavot', 'A2'),
(5, 'fruit', 'meva', 'A2'),
(5, 'sugar', 'shakar', 'A2'),
(5, 'salt', 'tuz', 'A2'),
(5, 'breakfast', 'nonushta', 'A2'),
(5, 'lunch', 'tushlik', 'A2'),
(5, 'dinner', 'kechki ovqat', 'A2'),
(5, 'hungry', 'och', 'A2'),
(6, 'today', 'bugun', 'A2'),
(6, 'tomorrow', 'ertaga', 'A2'),
(6, 'yesterday', 'kecha', 'A2'),
(6, 'now', 'hozir', 'A2'),
(6, 'later', 'keyinroq', 'A2'),
(6, 'early', 'erta', 'A2'),
(6, 'late', 'kech', 'A2'),
(6, 'morning', 'ertalab', 'A2'),
(6, 'afternoon', 'peshin', 'A2'),
(6, 'evening', 'kechqurun', 'A2'),
(6, 'night', 'tun', 'A2'),
(6, 'week', 'hafta', 'A2'),
(6, 'month', 'oy', 'A2'),
(6, 'year', 'yil', 'A2'),
(6, 'Monday', 'dushanba', 'A2'),
(6, 'Friday', 'juma', 'A2'),
(6, 'Sunday', 'yakshanba', 'A2'),
(6, 'clock', 'soat', 'A2'),
(6, 'calendar', 'kalendar', 'A2'),
(6, 'birthday', 'tug''ilgan kun', 'A2'),
(7, 'home', 'uy', 'A2'),
(7, 'school', 'maktab', 'A2'),
(7, 'hospital', 'kasalxona', 'A2'),
(7, 'shop', 'do''kon', 'A2'),
(7, 'park', 'park', 'A2'),
(7, 'station', 'stansiya', 'A2'),
(7, 'airport', 'aeroport', 'A2'),
(7, 'hotel', 'mehmonxona', 'A2'),
(7, 'bank', 'bank', 'A2'),
(7, 'library', 'kutubxona', 'A2'),
(7, 'museum', 'muzey', 'A2'),
(7, 'cinema', 'kino', 'A2'),
(7, 'restaurant', 'restoran', 'A2'),
(7, 'supermarket', 'supermarket', 'A2'),
(7, 'street', 'ko''cha', 'A2'),
(7, 'city', 'shahar', 'A2'),
(7, 'village', 'qishloq', 'A2'),
(7, 'map', 'xarita', 'A2'),
(7, 'bridge', 'ko''prik', 'A2'),
(7, 'office', 'idora', 'A2'),
(8, 'car', 'mashina', 'A2'),
(8, 'bus', 'avtobus', 'A2'),
(8, 'train', 'poyezd', 'A2'),
(8, 'plane', 'samolyot', 'A2'),
(8, 'bike', 'velosiped', 'A2'),
(8, 'boat', 'qayiq', 'A2'),
(8, 'walk', 'yurish', 'A2'),
(8, 'drive', 'haydash', 'A2'),
(8, 'ticket', 'chipta', 'A2'),
(8, 'road', 'yo''l', 'A2'),
(8, 'traffic', 'transport harakati', 'A2'),
(8, 'trip', 'sayohat', 'A2'),
(8, 'passenger', 'yo''lovchi', 'A2'),
(8, 'driver', 'haydovchi', 'A2'),
(8, 'stop', 'bekat', 'A2'),
(8, 'fast', 'tez', 'A2'),
(8, 'slow', 'sekin', 'A2'),
(8, 'far', 'uzoq', 'A2'),
(8, 'near', 'yaqin', 'A2'),
(8, 'map', 'xarita', 'A2'),
(9, 'shirt', 'ko''ylak', 'A2'),
(9, 'trousers', 'shim', 'A2'),
(9, 'dress', 'ko''ylak (ayol)', 'A2'),
(9, 'skirt', 'yubka', 'A2'),
(9, 'coat', 'palto', 'A2'),
(9, 'jacket', 'kurtka', 'A2'),
(9, 'shoes', 'oyoq kiyim', 'A2'),
(9, 'socks', 'paypoq', 'A2'),
(9, 'hat', 'shapka', 'A2'),
(9, 'gloves', 'qo''lqop', 'A2'),
(9, 'scarf', 'sharf', 'A2'),
(9, 'bag', 'sumka', 'A2'),
(9, 'glasses', 'ko''zoynak', 'A2'),
(9, 'uniform', 'forma', 'A2'),
(9, 'size', 'o''lcham', 'A2'),
(9, 'wear', 'kiyinish', 'A2'),
(9, 'buy', 'sotib olish', 'A2'),
(9, 'cheap', 'arzon', 'A2'),
(9, 'expensive', 'qimmat', 'A2'),
(9, 'colour', 'rang', 'A2'),
(10, 'weather', 'ob-havo', 'A2'),
(10, 'sunny', 'quyoshli', 'A2'),
(10, 'rainy', 'yomg''irli', 'A2'),
(10, 'cloudy', 'bulutli', 'A2'),
(10, 'windy', 'shamolli', 'A2'),
(10, 'snow', 'qor', 'A2'),
(10, 'cold', 'sovuq', 'A2'),
(10, 'hot', 'issiq', 'A2'),
(10, 'warm', 'iliq', 'A2'),
(10, 'spring', 'bahor', 'A2'),
(10, 'summer', 'yoz', 'A2'),
(10, 'autumn', 'kuz', 'A2'),
(10, 'winter', 'qish', 'A2'),
(10, 'degree', 'gradus', 'A2'),
(10, 'forecast', 'prognoz', 'A2'),
(10, 'climate', 'iqlim', 'A2'),
(10, 'dry', 'quruq', 'A2'),
(10, 'wet', 'ho''l', 'A2'),
(10, 'storm', 'bo''ron', 'A2'),
(10, 'rain', 'yomg''ir', 'A2'),
(11, 'sport', 'sport', 'A2'),
(11, 'football', 'futbol', 'A2'),
(11, 'basketball', 'basketbol', 'A2'),
(11, 'tennis', 'tennis', 'A2'),
(11, 'swimming', 'suzish', 'A2'),
(11, 'running', 'yugurish', 'A2'),
(11, 'team', 'jamoa', 'A2'),
(11, 'game', 'o''yin', 'A2'),
(11, 'win', 'yutmoq', 'A2'),
(11, 'lose', 'yutqazmoq', 'A2'),
(11, 'train', 'mashq qilmoq', 'A2'),
(11, 'match', 'o''yin', 'A2'),
(11, 'player', 'o''yinchi', 'A2'),
(11, 'coach', 'murabbiy', 'A2'),
(11, 'ball', 'to''p', 'A2'),
(11, 'hobby', 'qiziqish', 'A2'),
(11, 'fun', 'qiziqarli', 'A2'),
(11, 'race', 'poyga', 'A2'),
(11, 'goal', 'gol', 'A2'),
(11, 'rules', 'qoidalar', 'A2'),
(12, 'job', 'ish', 'A2'),
(12, 'work', 'ishlash', 'A2'),
(12, 'boss', 'boshliq', 'A2'),
(12, 'colleague', 'hamkasb', 'A2'),
(12, 'salary', 'maosh', 'A2'),
(12, 'holiday', 'ta''til', 'A2'),
(12, 'meeting', 'yig''ilish', 'A2'),
(12, 'email', 'email', 'A2'),
(12, 'phone', 'telefon', 'A2'),
(12, 'computer', 'kompyuter', 'A2'),
(12, 'desk', 'stol', 'A2'),
(12, 'teacher', 'o''qituvchi', 'A2'),
(12, 'doctor', 'shifokor', 'A2'),
(12, 'nurse', 'hamshira', 'A2'),
(12, 'police', 'politsiya', 'A2'),
(12, 'seller', 'sotuvchi', 'A2'),
(12, 'student', 'o''quvchi', 'A2'),
(12, 'science', 'fan', 'A2'),
(12, 'project', 'loyiha', 'A2'),
(12, 'deadline', 'muddat', 'A2'),
(13, 'one', 'bir', 'A2'),
(13, 'two', 'ikki', 'A2'),
(13, 'three', 'uch', 'A2'),
(13, 'four', 'to''rt', 'A2'),
(13, 'five', 'besh', 'A2'),
(13, 'six', 'olti', 'A2'),
(13, 'seven', 'yetti', 'A2'),
(13, 'eight', 'sakkiz', 'A2'),
(13, 'nine', 'to''qqiz', 'A2'),
(13, 'ten', 'o''n', 'A2'),
(13, 'first', 'birinchi', 'A2'),
(13, 'second', 'ikkinchi', 'A2'),
(13, 'third', 'uchinchi', 'A2'),
(13, 'half', 'yarim', 'A2'),
(13, 'money', 'pul', 'A2'),
(13, 'price', 'narx', 'A2'),
(13, 'percent', 'foiz', 'A2'),
(13, 'card', 'karta', 'A2'),
(13, 'cash', 'naqd', 'A2'),
(13, 'coin', 'tanga', 'A2'),
(14, 'buy', 'sotib olish', 'A2'),
(14, 'sell', 'sotish', 'A2'),
(14, 'market', 'bozor', 'A2'),
(14, 'pay', 'to''lash', 'A2'),
(14, 'receipt', 'kvitansiya', 'A2'),
(14, 'discount', 'chegirma', 'A2'),
(14, 'customer', 'xaridor', 'A2'),
(14, 'open', 'ochiq', 'A2'),
(14, 'closed', 'yopiq', 'A2'),
(14, 'free', 'bepul', 'A2'),
(14, 'change', 'qaytim', 'A2'),
(14, 'cheap', 'arzon', 'A2'),
(14, 'expensive', 'qimmat', 'A2'),
(14, 'size', 'o''lcham', 'A2'),
(14, 'cost', 'narx', 'A2'),
(14, 'wallet', 'hamyon', 'A2'),
(14, 'offer', 'taklif', 'A2'),
(14, 'bill', 'hisob', 'A2'),
(14, 'sale', 'chegirma sotuv', 'A2'),
(14, 'shop assistant', 'sotuvchi', 'A2'),
(15, 'speak', 'gapirish', 'A2'),
(15, 'listen', 'tinglash', 'A2'),
(15, 'read', 'o''qish', 'A2'),
(15, 'write', 'yozish', 'A2'),
(15, 'ask', 'so''ramoq', 'A2'),
(15, 'answer', 'javob bermoq', 'A2'),
(15, 'understand', 'tushunmoq', 'A2'),
(15, 'mean', 'demoq', 'A2'),
(15, 'repeat', 'takrorlash', 'A2'),
(15, 'translate', 'tarjima qilmoq', 'A2'),
(15, 'language', 'til', 'A2'),
(15, 'word', 'so''z', 'A2'),
(15, 'sentence', 'gap', 'A2'),
(15, 'conversation', 'suhbat', 'A2'),
(15, 'pronunciation', 'talaffuz', 'A2'),
(15, 'dictionary', 'lug''at', 'A2'),
(15, 'spell', 'harflab yozmoq', 'A2'),
(15, 'mistake', 'xato', 'A2'),
(15, 'correct', 'to''g''ri', 'A2'),
(15, 'practice', 'mashq', 'A2'),
(16, 'happy', 'baxtli', 'A2'),
(16, 'sad', 'g''amgin', 'A2'),
(16, 'angry', 'jahldor', 'A2'),
(16, 'tired', 'charchagan', 'A2'),
(16, 'worried', 'xavotirli', 'A2'),
(16, 'excited', 'hayajonli', 'A2'),
(16, 'nervous', 'asabiy', 'A2'),
(16, 'calm', 'xotirjam', 'A2'),
(16, 'proud', 'faxrlanmoq', 'A2'),
(16, 'afraid', 'qo''rqmoq', 'A2'),
(16, 'surprise', 'hayrat', 'A2'),
(16, 'feel', 'hissedmoq', 'A2'),
(16, 'love', 'sevmoq', 'A2'),
(16, 'hope', 'umid', 'A2'),
(16, 'pain', 'og''riq', 'A2'),
(16, 'smile', 'tabassum', 'A2'),
(16, 'cry', 'yig''lamoq', 'A2'),
(16, 'relax', 'dam olmoq', 'A2'),
(16, 'stress', 'stress', 'A2'),
(16, 'kind', 'mehribon', 'A2'),
(17, 'health', 'sog''liq', 'A2'),
(17, 'ill', 'kasal', 'A2'),
(17, 'medicine', 'dori', 'A2'),
(17, 'doctor', 'shifokor', 'A2'),
(17, 'hospital', 'kasalxona', 'A2'),
(17, 'better', 'yaxshiroq', 'A2'),
(17, 'fever', 'harorat', 'A2'),
(17, 'cough', 'yo''tal', 'A2'),
(17, 'headache', 'bosh og''rig''i', 'A2'),
(17, 'stomach', 'oshqozon', 'A2'),
(17, 'rest', 'dam olish', 'A2'),
(17, 'exercise', 'mashq', 'A2'),
(17, 'healthy', 'sog''lom', 'A2'),
(17, 'sick', 'kasal', 'A2'),
(17, 'pain', 'og''riq', 'A2'),
(17, 'dentist', 'tish shifokori', 'A2'),
(17, 'appointment', 'qabul', 'A2'),
(17, 'pharmacy', 'dorixona', 'A2'),
(17, 'vitamin', 'vitamin', 'A2'),
(17, 'sleep', 'uyqu', 'A2'),
(18, 'learn', 'o''rganmoq', 'A2'),
(18, 'study', 'o''qimoq', 'A2'),
(18, 'exam', 'imtihon', 'A2'),
(18, 'test', 'test', 'A2'),
(18, 'homework', 'uy vazifasi', 'A2'),
(18, 'class', 'sinf', 'A2'),
(18, 'notebook', 'daftar', 'A2'),
(18, 'pencil', 'qalam', 'A2'),
(18, 'ruler', 'chizgich', 'A2'),
(18, 'blackboard', 'doska', 'A2'),
(18, 'subject', 'fan', 'A2'),
(18, 'question', 'savol', 'A2'),
(18, 'answer', 'javob', 'A2'),
(18, 'mark', 'baho', 'A2'),
(18, 'pass', 'o''tmoq', 'A2'),
(18, 'fail', 'yiqilmoq', 'A2'),
(18, 'course', 'kurs', 'A2'),
(18, 'degree', 'daraja', 'A2'),
(18, 'certificate', 'sertifikat', 'A2'),
(18, 'library', 'kutubxona', 'A2'),
(19, 'internet', 'internet', 'A2'),
(19, 'website', 'sayt', 'A2'),
(19, 'password', 'parol', 'A2'),
(19, 'download', 'yuklab olish', 'A2'),
(19, 'upload', 'yuklash', 'A2'),
(19, 'file', 'fayl', 'A2'),
(19, 'screen', 'ekran', 'A2'),
(19, 'keyboard', 'klaviatura', 'A2'),
(19, 'mouse', 'sichqoncha', 'A2'),
(19, 'video', 'video', 'A2'),
(19, 'online', 'onlayn', 'A2'),
(19, 'offline', 'oflayn', 'A2'),
(19, 'app', 'ilova', 'A2'),
(19, 'wifi', 'Wi-Fi', 'A2'),
(19, 'battery', 'batareya', 'A2'),
(19, 'charger', 'zaryadlagich', 'A2'),
(19, 'click', 'bosmoq', 'A2'),
(19, 'save', 'saqlamoq', 'A2'),
(19, 'delete', 'o''chirmoq', 'A2'),
(19, 'search', 'qidiruv', 'A2'),
(20, 'travel', 'sayohat', 'A2'),
(20, 'passport', 'pasport', 'A2'),
(20, 'visa', 'viza', 'A2'),
(20, 'luggage', 'bagaj', 'A2'),
(20, 'border', 'chegara', 'A2'),
(20, 'foreign', 'chet', 'A2'),
(20, 'abroad', 'chet el', 'A2'),
(20, 'tour', 'tur', 'A2'),
(20, 'guide', 'gid', 'A2'),
(20, 'beach', 'plyaj', 'A2'),
(20, 'mountain', 'tog''', 'A2'),
(20, 'island', 'orol', 'A2'),
(20, 'camera', 'fotoaparat', 'A2'),
(20, 'souvenir', 'sovga', 'A2'),
(20, 'map', 'xarita', 'A2'),
(20, 'ticket', 'chipta', 'A2'),
(20, 'hotel', 'mehmonxona', 'A2'),
(20, 'flight', 'parvoz', 'A2'),
(20, 'visitor', 'mehmon', 'A2'),
(20, 'reservation', 'bron', 'A2'),
(21, 'kitchen', 'oshxona', 'A2'),
(21, 'bathroom', 'hammom', 'A2'),
(21, 'bedroom', 'yotoqxona', 'A2'),
(21, 'living room', 'mehmonxona', 'A2'),
(21, 'door', 'eshik', 'A2'),
(21, 'window', 'deraza', 'A2'),
(21, 'floor', 'qavat', 'A2'),
(21, 'roof', 'tom', 'A2'),
(21, 'shelf', 'jarf', 'A2'),
(21, 'table', 'stol', 'A2'),
(21, 'chair', 'stul', 'A2'),
(21, 'lamp', 'chiroq', 'A2'),
(21, 'key', 'kalit', 'A2'),
(21, 'rent', 'ijara', 'A2'),
(21, 'electricity', 'elektr', 'A2'),
(21, 'noise', 'shovqin', 'A2'),
(21, 'neighbour', 'qo''shn', 'A2'),
(21, 'flat', 'kvartira', 'A2'),
(21, 'stairs', 'zina', 'A2'),
(21, 'garden', 'bog''', 'A2'),
(22, 'because', 'chunki', 'A2'),
(22, 'but', 'lekin', 'A2'),
(22, 'and', 'va', 'A2'),
(22, 'or', 'yoki', 'A2'),
(22, 'so', 'shuning uchun', 'A2'),
(22, 'if', 'agar', 'A2'),
(22, 'when', 'qachon', 'A2'),
(22, 'before', 'oldin', 'A2'),
(22, 'after', 'keyin', 'A2'),
(22, 'then', 'keyin', 'A2'),
(22, 'also', 'ham', 'A2'),
(22, 'very', 'juda', 'A2'),
(22, 'always', 'doim', 'A2'),
(22, 'never', 'hech qachon', 'A2'),
(22, 'sometimes', 'ba''zan', 'A2'),
(22, 'often', 'tez-teq', 'A2'),
(22, 'maybe', 'balki', 'A2'),
(22, 'both', 'ikkisi ham', 'A2'),
(22, 'another', 'boshqa', 'A2'),
(22, 'same', 'xuddi shu', 'A2'),
(23, 'go', 'bormoq', 'A2'),
(23, 'come', 'kelmoq', 'A2'),
(23, 'leave', 'ketmoq', 'A2'),
(23, 'arrive', 'yetib kelmoq', 'A2'),
(23, 'stay', 'qolmoq', 'A2'),
(23, 'visit', 'tashrif buyurmoq', 'A2'),
(23, 'return', 'qaytmoq', 'A2'),
(23, 'fly', 'uchmoq', 'A2'),
(23, 'walk', 'yurmoq', 'A2'),
(23, 'run', 'yugurmoq', 'A2'),
(23, 'sit', 'o''tirmoq', 'A2'),
(23, 'stand', 'turmoq', 'A2'),
(23, 'open', 'ochmoq', 'A2'),
(23, 'close', 'yopmoq', 'A2'),
(23, 'start', 'boshlamoq', 'A2'),
(23, 'finish', 'tugatmoq', 'A2'),
(23, 'bring', 'olib kelmoq', 'A2'),
(23, 'take', 'olib ketmoq', 'A2'),
(23, 'put', 'qo''ymoq', 'A2'),
(23, 'wait', 'kutmoq', 'A2'),
(24, 'cook', 'pishirmoq', 'A2'),
(24, 'cut', 'to''g''ramoq', 'A2'),
(24, 'boil', 'qaynatmoq', 'A2'),
(24, 'fry', 'qovurmoq', 'A2'),
(24, 'bake', 'pishirmoq (duxovkada)', 'A2'),
(24, 'taste', 'ta''m', 'A2'),
(24, 'delicious', 'mazali', 'A2'),
(24, 'sweet', 'shirin', 'A2'),
(24, 'sour', 'nordon', 'A2'),
(24, 'salty', 'tuzli', 'A2'),
(24, 'fresh', 'yangi', 'A2'),
(24, 'knife', 'picho', 'A2'),
(24, 'fork', 'vilka', 'A2'),
(24, 'spoon', 'qoshiq', 'A2'),
(24, 'plate', 'likop', 'A2'),
(24, 'recipe', 'retsept', 'A2'),
(24, 'oil', 'yog''', 'A2'),
(24, 'meal', 'taom', 'A2'),
(24, 'snack', 'yengil ovqat', 'A2'),
(24, 'dish', 'taom', 'A2'),
(25, 'tree', 'daraxt', 'A2'),
(25, 'flower', 'gul', 'A2'),
(25, 'grass', 'o''t', 'A2'),
(25, 'river', 'daryo', 'A2'),
(25, 'lake', 'ko''l', 'A2'),
(25, 'sea', 'dengiz', 'A2'),
(25, 'forest', 'o''rmon', 'A2'),
(25, 'sky', 'osmon', 'A2'),
(25, 'star', 'yulduz', 'A2'),
(25, 'moon', 'oy', 'A2'),
(25, 'earth', 'yer', 'A2'),
(25, 'plant', 'o''simlik', 'A2'),
(25, 'environment', 'atrof-muhit', 'A2'),
(25, 'air', 'havo', 'A2'),
(25, 'pollution', 'ifloslanish', 'A2'),
(25, 'protect', 'himoya qilmoq', 'A2'),
(25, 'animal', 'hayvon', 'A2'),
(25, 'bird', 'qush', 'A2'),
(25, 'nature', 'tabiat', 'A2'),
(25, 'weather', 'ob-havo', 'A2'),
(26, 'music', 'musiqa', 'A2'),
(26, 'song', 'qo''shiq', 'A2'),
(26, 'film', 'film', 'A2'),
(26, 'photo', 'rasm', 'A2'),
(26, 'dance', 'raqs', 'A2'),
(26, 'book', 'kitob', 'A2'),
(26, 'story', 'hikoya', 'A2'),
(26, 'art', 'san''at', 'A2'),
(26, 'picture', 'rasm', 'A2'),
(26, 'draw', 'chizmoq', 'A2'),
(26, 'fun', 'qiziqarli', 'A2'),
(26, 'boring', 'zerikarli', 'A2'),
(26, 'free time', 'bo''sh vaqt', 'A2'),
(26, 'weekend', 'hafta oxiri', 'A2'),
(26, 'party', 'ziyofat', 'A2'),
(26, 'concert', 'konsert', 'A2'),
(26, 'instrument', 'asbob', 'A2'),
(26, 'theatre', 'teatr', 'A2'),
(26, 'museum', 'muzey', 'A2'),
(26, 'hobby', 'qiziqish', 'A2'),
(27, 'people', 'odamlar', 'A2'),
(27, 'friend', 'do''st', 'A2'),
(27, 'neighbor', 'qo''shn', 'A2'),
(27, 'stranger', 'begona', 'A2'),
(27, 'young', 'yosh', 'A2'),
(27, 'old', 'qari', 'A2'),
(27, 'rich', 'boy', 'A2'),
(27, 'poor', 'kambag''al', 'A2'),
(27, 'help', 'yordam', 'A2'),
(27, 'culture', 'madaniyat', 'A2'),
(27, 'tradition', 'an''ana', 'A2'),
(27, 'law', 'qonun', 'A2'),
(27, 'right', 'huquq', 'A2'),
(27, 'polite', 'xushmuomala', 'A2'),
(27, 'rude', 'qo''pol', 'A2'),
(27, 'kind', 'mehribon', 'A2'),
(27, 'honest', 'halol', 'A2'),
(27, 'important', 'muhim', 'A2'),
(27, 'problem', 'muammo', 'A2'),
(27, 'community', 'jamiyat', 'A2'),
(28, 'safe', 'xavfsiz', 'A2'),
(28, 'danger', 'xavf', 'A2'),
(28, 'fire', 'olov', 'A2'),
(28, 'accident', 'baxtsiz hodisa', 'A2'),
(28, 'emergency', 'favqulodda', 'A2'),
(28, 'warning', 'ogohlantirish', 'A2'),
(28, 'rule', 'qoida', 'A2'),
(28, 'helmet', 'kaska', 'A2'),
(28, 'seat belt', 'kamar', 'A2'),
(28, 'slow', 'sekinroq', 'A2'),
(28, 'careful', 'ehtiyotkor', 'A2'),
(28, 'help', 'yordam', 'A2'),
(28, 'call', 'qo''ng''iroq qilmoq', 'A2'),
(28, 'police', 'politsiya', 'A2'),
(28, 'hurt', 'jarohat', 'A2'),
(28, 'risk', 'risk', 'A2'),
(28, 'protect', 'himoya qilmoq', 'A2'),
(28, 'stairs', 'zina', 'A2'),
(28, 'crossing', 'o''tish joyi', 'A2'),
(28, 'traffic lights', 'svetafor', 'A2'),
(29, 'plan', 'reja', 'A2'),
(29, 'dream', 'orzu', 'A2'),
(29, 'future', 'kelajak', 'A2'),
(29, 'hope', 'umid', 'A2'),
(29, 'goal', 'maqsad', 'A2'),
(29, 'success', 'muvaffaqiyat', 'A2'),
(29, 'fail', 'muvaffaqiyatsiz', 'A2'),
(29, 'maybe', 'balki', 'A2'),
(29, 'probably', 'ehtimol', 'A2'),
(29, 'must', 'kerak (majburiy)', 'A2'),
(29, 'should', 'kerak (maslahat)', 'A2'),
(29, 'would like', 'xohlardi', 'A2'),
(29, 'predict', 'bashorat qilmoq', 'A2'),
(29, 'prepare', 'tayyorlanmoq', 'A2'),
(29, 'decide', 'qaror qilmoq', 'A2'),
(29, 'choose', 'tanlamoq', 'A2'),
(29, 'try', 'urinmoq', 'A2'),
(29, 'believe', 'ishonmoq', 'A2'),
(29, 'remember', 'eslamoq', 'A2'),
(29, 'forget', 'unutmoq', 'A2'),
(30, 'almost', 'deyarli', 'A2'),
(30, 'already', 'allaqachon', 'A2'),
(30, 'still', 'hali ham', 'A2'),
(30, 'again', 'yana', 'A2'),
(30, 'easy', 'oson', 'A2'),
(30, 'difficult', 'qiyin', 'A2'),
(30, 'possible', 'mumkin', 'A2'),
(30, 'impossible', 'mumkin emas', 'A2'),
(30, 'certainly', 'albatta', 'A2'),
(30, 'perhaps', 'balki', 'A2'),
(30, 'finally', 'nihoyat', 'A2'),
(30, 'suddenly', 'to''satdan', 'A2'),
(30, 'especially', 'ayniqsa', 'A2'),
(30, 'usually', 'odatda', 'A2'),
(30, 'recently', 'yaqinda', 'A2'),
(30, 'eventually', 'oxir-oqibat', 'A2'),
(30, 'clearly', 'aniq', 'A2'),
(30, 'probably', 'ehtimol', 'A2'),
(30, 'exactly', 'aynan', 'A2'),
(30, 'instead', 'o''rniga', 'A2');
